### ISSUE TITLE
Config-Page anpassen

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/demo_addon#10]
Die Config-Page ist noch etwas arg schlicht und entspricht nicht den aktuellen Standards. Den Fragmenten fehlen die `.form-control`-Klassen, und die Buttonleiste ist nicht aktuell.

Das sollten wir auf den aktuellen Stand bringen und z. B. noch um einen `.help-block` ergänzen.

<img width="1279" alt="screenshot 2016-10-26 23 03 10" src="https://cloud.githubusercontent.com/assets/1297466/19745092/89b4f69e-9bd0-11e6-84bb-35b4ed19fb39.png">

**Comment by schuer** [comment]
Siehe auch #8

**Comment by schuer** [comment]
Hat @aeberhard gefixt mit #5

**Comment by schuer** [comment]
Ah, noch nicht vollständig erledigt. Ich mach’s nochmal auf und kümmere mich bei Gelegenheit drum.

**Comment by alexplusde** [comment]
Kann man das Projekt bis zum Redaxo-Tag pushen? Addons sind doch etwas, in das einige m.E. den Einstieg nicht finden, dabei ist es eigentlich nicht so schwer. Wie kann ich da unterstützend eingreifen?

**Comment by schuer** [comment]
Ist evtl. mit #15 implementiert worden. Müsste nochmal abschließend geprüft werden.

**Comment by schuer** [comment]
Geprüft, passt! Der @aeberhard hatte das längst gerockt. 👍
