### ISSUE TITLE
package.yml validiert nicht

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/demo_addon#11]
Es sind Tabs/Leerzeichen drin, und es fehlen Anführungszeichen innerhalb der geschweiften Klammern.

Siehe http://yaml-online-parser.appspot.com

**Comment by gharlan** [comment]
Nur zur Erklärung: In der Anfangszeit von R5 war noch eine ältere Version des Symfony-Yaml-Parsers enthalten, der da 'gnädiger' war.
