### ISSUE TITLE
Fehler in Template Header

### ISSUE THREAD

**Issue by sebhecht** [FriendsOfREDAXO/demo_addon#16]
In Zeile 10 muss die Bedingung
`while ($headerpic == '') {...` 
und nicht 
` while ($header == '') {` 
lauten.
Sonst wird das Headerpic der Elternkategorie nicht übernommen.

**Comment by schuer** [comment]
Hey, sorry dass das jetzt erst auffällt: Dieses Issue ist im falschen Repo gelandet und gehört offenbar in `demo_base`! Ich kann es nicht verschieben, magst du es bitte nochmal dort neu anlegen, @sebhecht. (Wenn ich es machte, stünde ich als Autor dort, aber das sollst ja weiterhin du sein.)

Danke!
