### ISSUE TITLE
Fehler in der YML Datei

### ISSUE THREAD

**Issue by Hirbod** [FriendsOfREDAXO/demo_addon#18]
Hi,

gerade erst begonnen, bisschen die AddOn Thematik in REX5 zu verstehen.
Ein Fehler ist jedoch gleich aufgetreten, als ich mir das Addon installieren wollte:

```yml
 version: '^5.6' # benötigt mindestens PHP 5.6
```
Caret bedeutet eigentlich >= 5.6 und < 6.0.0 und nicht mindestens 5.6

`>=` 5.6 müsste da eigentlich stehen. Das AddOn ist bei mir z.B. nicht mittels PHP 7 installierbar.

https://getcomposer.org/doc/articles/versions.md

**Comment by gharlan** [comment]
Ja stimmt, bei der PHP-Version sollte man immer mit `>=` arbeiten (also nach oben hin nicht einschränken), nicht mit dem `^`-Operator.
(Bei den anderen Abhängigkeiten hingegen schon.)

**Comment by staabm** [comment]
kleine Korrektur: bei packeten/tools/whatever die nach semantic versioning arbeiten sollte man `^` verwenden, bei allen anderen je nach versionierungsschema das passende (z.b. `1.2.*` etc).

Versionsangaben mit offenem Intervall nach oben sind generell nicht empfehlenswert.

**Comment by gharlan** [comment]
> @gharlan unterstützuen wir || in constraints?

Nein, nur `,` (quasi `and`).

**Comment by Hirbod** [comment]
Ändert nichts daran, das die Aussage "mindestens 5.6" hier falsch ist, da 6.0.0 schon zum Fehler führen würde. Da das AddOn aber getestet auf PHP 7 läuft und || aktuell nicht läuft, wäre doch

`>= 5.6.0 <= 8.0.0` vorerst die richtige Lösung, oder?

**Comment by Hirbod** [comment]
Vergesst meinen Vorschlag, funktioniert nicht
