### ISSUE TITLE
Project lead?

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/demo_addon#19]
[Gregor will nicht mehr](https://github.com/FriendsOfREDAXO/demo_addon/issues/6#issuecomment-255680463). Gibt es jemanden, der Lust hat — @aeberhard etwa, du warst zuletzt dran —, oder lassen wir es ohne Lead laufen?

Ich greife das Thema übrigens deshalb wieder auf, weil https://friendsofredaxo.github.io nun die Leads zeigt, und ich mir bei diesem Addon unschlüssig war ;)

**Comment by aeberhard** [comment]
Klar @schuer mach mal mich rein :)

**Comment by schuer** [comment]
Cool, erledigt!
