### ISSUE TITLE
Extension Point Beispiel mit aufnehmen

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/demo_addon#2]

**Comment by tbaddade** [comment]
Ich schließe wegen Inaktivität.

**Comment by aeberhard** [comment]
Da bin ich gerade mit einem umfangreichen Fork dran.
Hier wird es erweiterbare Beispiele für EP's geben ...

**Comment by tbaddade** [comment]
> Da bin ich gerade mit einem umfangreichen Fork dran.
> Hier wird es erweiterbare Beispiele für EP's geben

Das liest sich doch gut :)

**Comment by aeberhard** [comment]
https://github.com/FriendsOfREDAXO/demo_addon/pull/55
