### ISSUE TITLE
neuste Demo Version lässt sich nicht installieren

### ISSUE THREAD

**Issue by Kalle01** [FriendsOfREDAXO/demo_addon#20]
Fehlermeldung:

AddOn demo_base konnte aus folgendem Grund nicht installiert werden:
Es wird das AddOn textile benötigt!
Es wird das AddOn rex_markitup benötigt!

rex markitup gibt es nicht mehr
markitup und textile lassen sich nicht gleichzeitg aktivieren

**Comment by gharlan** [comment]
Du bist hier im falschen Repo, dies ist das demo_addon, also ein Beispiel-Addon zum Lernen wie man Addons erstellen kann.
Du willst aber wohl hier hin: https://github.com/FriendsOfREDAXO/demo_base

**Comment by polarpixel** [comment]
@Kalle01: Kann es sein, dass Du irgendeine alte Version hast?
In der aktuellen Version und auch in der vorherigen sollte das schon korrigiert sein:
https://github.com/FriendsOfREDAXO/demo_base/blob/master/package.yml

So oder so: Hier an dieser Stelle können wir das Issue schließen, glaube ich.

**Comment by Kalle01** [comment]
sorry!
