### ISSUE TITLE
rex_form in den Beispielen nutzen

### ISSUE THREAD

**Issue by cukabeka** [FriendsOfREDAXO/demo_addon#25]
Zumindest als zusätzliche Page, um eine Vorlage zu haben, wie man den core nutzt, um Addon-Inpouts zu bauen.

https://redaxo.org/doku/master/formulare

Siehe auch [Slack](https://friendsofredaxo.slack.com/archives/C1BAXLN2F/p1508932248000191)

**Comment by aeberhard** [comment]
https://github.com/FriendsOfREDAXO/demo_addon/pull/55
