### ISSUE TITLE
Mehrsprachigkeit

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/demo_addon#26]
Ich fände es cool, wenn wir das Demo-AddOn bereit machen könnten für Nicht-Deutschsprachler. Demos sind vermutlich oft ein erster Anknüpftpunkt für neue REDAXO-Nutzer, deshalb sollten gerade Demos möglichst auch auf Englisch verfügbar gemacht werden. Inklusive README und allem drum und dran.

**Comment by aeberhard** [comment]
Nach der Überarbeitung ist soweit ich es geprüft habe so gut wie alles Mehrsprachig!
https://github.com/FriendsOfREDAXO/demo_addon/pull/55

**Comment by schuer** [comment]
Super, @aeberhard! 🙌 
Dann kann doch wirklich hier geschlossen werden, oder?

**Comment by aeberhard** [comment]
Also ich habe alles mehrsprachig aufgebaut, sind natürlich nur deutsche .md-Dateien vorhanden. Nur die README hab ich übersetzt. Ich mach dann mal zu :)
