### ISSUE TITLE
Beispiel Tabellenverwaltung

### ISSUE THREAD

**Issue by aeberhard** [FriendsOfREDAXO/demo_addon#31]
Beispiel einer Tabellenverwaltung mit rex_form
- Liste
- Edit
- Feld formatieren, z.B. Datum
- Selectfeld mit Werten aus anderer Tabelle

Liste für Beispiele am besten hier erweitern oder als Kommentar

siehe auch #25

**Comment by cukabeka** [comment]
Fände spannend, möglichst einfache Ansätze kennenzulernen, evtl in Kombination mit Yform - im TabellenManager werden ja bereits die Möglichkeiten mitgeliefert, neue Datensätze anzulegen. Vielleicht lässt sich das auch in Addons weiterverwenden?

**Comment by aeberhard** [comment]
@cukabeka geplant ist eine Tabellenverwaltung auf Basis von rex_list, mit ein paar Feinheiten.

**Comment by cukabeka** [comment]
Klingt gut, und evtl hilft es auch vielen anderen, sich die Kombination mit yform anzuschauen: https://friendsofredaxo.github.io/tricks/addons_yform_im-addon.html

**Comment by aeberhard** [comment]
https://github.com/FriendsOfREDAXO/demo_addon/pull/55
