### ISSUE TITLE
Doku-Dummy als Plugin

### ISSUE THREAD

**Issue by aeberhard** [FriendsOfREDAXO/demo_addon#4]
Doku-Dummy als Plugin ist in Arbeit

Siehe https://github.com/FriendsOfREDAXO/Info/issues/21

@schuer @tyrant88 @alexplusde

**Comment by alexplusde** [comment]
Wer hat's erfunden? Der @dergel.

**Comment by aeberhard** [comment]
Erste Version mal zum drüberschauen ist da ...
https://github.com/aeberhard/dummy_documentation

**Comment by schuer** [comment]
Ist mit #17 implementiert worden.
