### ISSUE TITLE
demo-Addon auf redaxo.org nicht sichtbar

### ISSUE THREAD

**Issue by aeberhard** [FriendsOfREDAXO/demo_addon#47]
Das Addon ist im Downloadbereich von redaxo.org nicht sichtbar!?
Im Installer aber verfügbar!

https://redaxo.org/download/addons/?q=demo
https://redaxo.org/download/addons/?q=demo_addon

@dergel @gharlan

**Comment by schuer** [comment]
Das AddOn wurde nie veröffentlicht. Vermutlich deshalb nicht, weil es nie eine echte nützliche Funktion hatte, sondern nur Code zeigen sollte. Dementsprechend sind wir bisher immer davon ausgegangen, dass der Code bei GitHub ausreicht und kein Release im Installer benötigt wird.

**Comment by schuer** [comment]
Oh sorry, zu schnell gelesen. In der Tat ist das AddOn im Installer, du hast recht. Eigenartig ¯\_(ツ)_/¯

**Comment by aeberhard** [comment]
@schuer wenn ich mich recht erinnere hast sogar Du die 1. Version bereitgestellt :)

**Comment by schuer** [comment]
Da ist es: https://redaxo.org/download/addons/demo_addon/

Das Wort »Demo« kommit nirgendwo im Text vor, nur im AddOn-Key. Vielleicht greift die Suche darauf nicht.

**Comment by aeberhard** [comment]
Jo du hast Recht @schuer Dirk, habe den Text angepasst und dann klappt auch die Suche!
https://redaxo.org/download/addons/?q=demo
