### ISSUE TITLE
Beispiel Settings Page

### ISSUE THREAD

**Issue by cukabeka** [FriendsOfREDAXO/demo_addon#49]
Ein Beispiel, wie man einfache Einstellungen mit Rex Widgets nutzt und wie diese im data Ordner gespeichert werden. 

Nützlich wären als Beispiel
- Text
- Textarea
- Media
- evtl was mit JS-Widget, zB Colorpicker

**Comment by cukabeka** [comment]
Sehr schönes Beispiel von @tbaddade hier und was angepasst werden muss: 
https://gist.github.com/tbaddade/8f60d535a0df51daf55f623eb572549d#file-settings-php-L81

Siehe mehr zu Link_widgets etc in Slack: https://friendsofredaxo.slack.com/archives/C1BAXLN2F/p1525717826000290?thread_ts=1525711076.000182&cid=C1BAXLN2F

**Comment by aeberhard** [comment]
https://github.com/FriendsOfREDAXO/demo_addon/pull/55
