### ISSUE TITLE
Demo PlugIn: Hinweis zum Handhaben des Tabellenprefix aufnehmen

### ISSUE THREAD

**Issue by madiko** [FriendsOfREDAXO/demo_addon#52]
Hinweis von KOALA (https://friendsofredaxo.slack.com/team/U1S9MKBKR)
vom 08.12.2018 01:28 

*Ein Aufruf an alle Entwickler von Addons hier.*

Mir fliegt hier grad eine Redaxoinstallation um die Ohren, weil in einigen Addons die Datenbanktabellen fest mit dem Prefix "rex_" verdongelt sind. Damit funktioniert eine Installation über den R5-eigenen Installer nicht mehr, wenn in der Grundkonfiguration ein anderes Tabellenprefix angegeben wurde!

Solche Dinge sind einfach nur tödlich:
`$db->setQuery('DELETE FROM `rex_media_manager_type`  WHERE `type_id`="'.$id.'";');`

So müsste es z.B. sein (allerdings ungetestet):
`$db->setQuery('DELETE FROM `' . rex::getTablePrefix() . 'media_manager_type`  WHERE `type_id`="'.$id.'";');`

**Comment by aeberhard** [comment]
https://github.com/FriendsOfREDAXO/demo_addon/pull/55

mit dem PR erledigt!?
