### ISSUE TITLE
config-seite mit rex_config_form

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/demo_addon#54]

**Comment by aeberhard** [comment]
Kommt mit der Version 1.2 daher hier close

**Comment by skerbis** [comment]
Ok. Ich hatte mich assigned - wenn du es machst ok 👌

**Comment by aeberhard** [comment]
@skerbis :) aber vielleicht weisst Du ja hierzu was:
https://github.com/FriendsOfREDAXO/demo_addon/pull/55#discussion_r373735881
