### ISSUE TITLE
Addon-Name: Umbenennen in `demo_addon`?

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/demo_addon#6]
Eben bei Slack mit @aeberhard drüber gesprochen, der das Doku-Plugin (#4) baut: Sollten wir das Addon nicht vielleicht etwas treffender benennen? »Dummy« ist irgendwie eher ein Platzhalter als eine Demonstration von Funktionalität.

Wie wäre es also mit `demo_addon`?

**Comment by skerbis** [comment]
Was macht dieses Addon? ... ist es nicht eher sowas wie ein Addon-Skeleton? (reimt sich sogar)

**Comment by aeberhard** [comment]
Also ich bin für `demo_addon`
Sehe das nicht als Skeleton sondern eher als Sammelsurium mit nützlichen Beispielen für die Addon-Entwicklung

**Comment by schuer** [comment]
Wir müssen vor allem noch auf @gharlan s Meinung warten.

**Comment by skerbis** [comment]
Oder Sample-Addon?

**Comment by gharlan** [comment]
`demo_addon` könnte auch falsch verstanden werden, als eine dritte Demo-Website, die vor allem den Umgang mit Addons zeigt, oder so.

Aber bin trotzdem auch einverstanden mit dem Namen, `dummy` finde ich auch nicht wirklich gut.
Als Skeleton sehe ich es auch eher nicht an, auch wenn man es trotzdem als Basis nehmen kann (und alles rauslöscht, was man nicht braucht).

Möchte bei diesem Addon übrigens auch nicht wirklich Lead sein, auch wenn ich es mal (auf die Schnelle) gestartet habe.
Helfe aber trotzdem auch gerne weiter mit. Wobei ich mir damals wie heute unsicher bin, wie weit man in dem Addon gehen soll (nur Basis-Dinge zeigen, oder möglichst viel reinpacken). Bin da für jede Richtung offen.

**Comment by schuer** [comment]
`demo_addon` würde wirklich gut zu `demo_base` und `demo_community` passen, wie @aeberhard schreibt. Und eigentlich soll es auch genau das sein: eine schlichte Demo, wie Addons für R5 aufgebaut sind, oder?

Meine Meinung zum Umfang: Ich würde nicht allzu viel reinpacken, sondern nur das, was als Basis für fast jedes Addon wichtig ist. Die typischen i18n-, package- und lib-Dinge, also. Eigentlich ist es schon fast »fertig«, finde ich. Zumindest funktioniert es schon sehr gut als Einstieg für R4-Umsteiger.

Ist nun also Konsens, dass es in `demo_addon` umbenannt wird? Wer dagegen ist, soll sich nochmal bemerkbar machen. Schweigen gilt als Zustimmung :)

P.S.: Ich möchte auch nicht Lead sein. Aber das Ding ist auch so schlicht, dass es vermutlich auch ohne Lead auskommt? Könnten wir mal testen…

**Comment by aeberhard** [comment]
Bin auch für Demo-Addon, und man kann ja den Sinn und Zweck des Demo_addons in die Readme schreiben. Würde das Addon auch noch um nütliche Beispiele usw. und vor allem um das documentation-Plugin erweitern
